
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 06 13:35:49 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 52;
  public static final int CONST = 8;
  public static final int CHAR = 14;
  public static final int HASH = 57;
  public static final int PRIVATE = 42;
  public static final int CONTINUE = 38;
  public static final int LPAREN = 25;
  public static final int SEMI = 9;
  public static final int FOR = 36;
  public static final int MINUS = 31;
  public static final int RPAREN = 26;
  public static final int AND = 53;
  public static final int LT = 51;
  public static final int OR = 54;
  public static final int BOOL = 16;
  public static final int COMMA = 10;
  public static final int CLASS = 44;
  public static final int INC = 34;
  public static final int DIV = 30;
  public static final int DIVEQUAL = 21;
  public static final int PLUS = 29;
  public static final int IF = 46;
  public static final int DOT = 12;
  public static final int ABSTRACT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 3;
  public static final int EQUAL = 17;
  public static final int NEW = 6;
  public static final int error = 1;
  public static final int MUL = 33;
  public static final int PLUSEQUAL = 18;
  public static final int NUMBER = 13;
  public static final int MOD = 32;
  public static final int NEQ = 48;
  public static final int BREAK = 39;
  public static final int VOID = 7;
  public static final int EQ = 47;
  public static final int GTE = 50;
  public static final int FOREACH = 37;
  public static final int COLON = 11;
  public static final int ELSE = 55;
  public static final int LBRACE = 23;
  public static final int PROTECTED = 41;
  public static final int LSQUARE = 27;
  public static final int READ = 5;
  public static final int MINUSEQUAL = 19;
  public static final int RSQUARE = 28;
  public static final int PUBLIC = 40;
  public static final int RBRACE = 24;
  public static final int EXTENDS = 45;
  public static final int PROG = 2;
  public static final int MODEQUAL = 22;
  public static final int STRING = 15;
  public static final int DEC = 35;
  public static final int MAX = 56;
  public static final int GT = 49;
  public static final int MULEQUAL = 20;
  public static final int PRINT = 4;
}

